language: objective-c
osx_image: xcode8
script:
  - xcodebuild clean test -project KRActivityIndicatorView.xcodeproj -scheme KRActivityIndicatorView -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0'

