source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'KRActivityIndicatorViewDemo' do
  use_frameworks!

  pod 'KRActivityIndicatorView', path: '../KRActivityIndicatorView.podspec'

end
